// Namma Metro station list, seeded into MongoDB on first run.
// Station ids encode line and physical order (PL01..PL37, GL01..GL32, YL01..YL16);
// routePlanner.js relies on that ordering to connect adjacent stations.
// Stations sharing a name across lines are interchanges (Majestic, RV Road).

const allStations = [
      // PURPLE LINE (37 stations)
      { stationId: 'PL01', name: 'Whitefield (Kadugodi)', line: 'purple', type: 'tech_hub', operational: true },
      { stationId: 'PL02', name: 'Hopefarm Channasandra', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL03', name: 'Kadugodi Tree Park', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL04', name: 'Pattandur Agrahara', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL05', name: 'Sri Sathya Sai Hospital', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL06', name: 'Nallurhalli', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL07', name: 'Kundalahalli', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL08', name: 'Seetharampalya', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL09', name: 'Hoodi', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL10', name: 'Garudacharpalya', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL11', name: 'Singayyanapalya', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL12', name: 'Krishnarajapura', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL13', name: 'Benniganahalli', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL14', name: 'Baiyappanahalli', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL15', name: 'Swami Vivekananda Road', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL16', name: 'Indiranagar', line: 'purple', type: 'business_district', operational: true },
      { stationId: 'PL17', name: 'Halasuru', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL18', name: 'Trinity', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL19', name: 'MG Road', line: 'purple', type: 'interchange', operational: true },
      { stationId: 'PL20', name: 'Cubbon Park', line: 'purple', type: 'business_district', operational: true },
      { stationId: 'PL21', name: 'Vidhana Soudha', line: 'purple', type: 'business_district', operational: true },
      { stationId: 'PL22', name: 'Central College', line: 'purple', type: 'business_district', operational: true },
      { stationId: 'PL23', name: 'Majestic', line: 'purple', type: 'interchange', operational: true },
      { stationId: 'PL24', name: 'City Railway Station', line: 'purple', type: 'business_district', operational: true },
      { stationId: 'PL25', name: 'Magadi Road', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL26', name: 'Hosahalli', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL27', name: 'Vijayanagar', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL28', name: 'Attiguppe', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL29', name: 'Deepanjali Nagar', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL30', name: 'Mysuru Road', line: 'purple', type: 'mid_line', operational: true },
      { stationId: 'PL31', name: 'Nayandahalli', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL32', name: 'Rajarajeshwari Nagar', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL33', name: 'Jnanabharathi', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL34', name: 'Pattanagere', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL35', name: 'Kengeri Bus Terminal', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL36', name: 'Kengeri', line: 'purple', type: 'residential_area', operational: true },
      { stationId: 'PL37', name: 'Challaghatta', line: 'purple', type: 'residential_area', operational: true },

      // GREEN LINE (32 stations)
      { stationId: 'GL01', name: 'Madavara', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL02', name: 'Chikkabidarakallu', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL03', name: 'Manjunathanagara', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL04', name: 'Nagasandra', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL05', name: 'Dasarahalli', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL06', name: 'Jalahalli', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL07', name: 'Peenya Industry', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL08', name: 'Peenya', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL09', name: 'Goraguntepalya', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL10', name: 'Yeshwanthpur', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL11', name: 'Sandal Soap Factory', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL12', name: 'Mahalakshmi', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL13', name: 'Rajajinagar', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL14', name: 'Kuvempu Road', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL15', name: 'Srirampura', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL16', name: 'Mantri Square Sampige Road', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL17', name: 'Majestic', line: 'green', type: 'interchange', operational: true },
      { stationId: 'GL18', name: 'Chickpete', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL19', name: 'KR Market', line: 'green', type: 'business_district', operational: true },
      { stationId: 'GL20', name: 'National College', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL21', name: 'Lalbagh', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL22', name: 'South End Circle', line: 'green', type: 'mid_line', operational: true },
      { stationId: 'GL23', name: 'Jayanagar', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL24', name: 'RV Road', line: 'green', type: 'interchange', operational: true },
      { stationId: 'GL25', name: 'Banashankari', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL26', name: 'JP Nagar', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL27', name: 'Yelachenahalli', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL28', name: 'Konanakunte Cross', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL29', name: 'Doddakallasandra', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL30', name: 'Vajarahalli', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL31', name: 'Talaghattapura', line: 'green', type: 'residential_area', operational: true },
      { stationId: 'GL32', name: 'Silk Institute', line: 'green', type: 'residential_area', operational: true },

      // YELLOW LINE (16 stations)
      { stationId: 'YL01', name: 'RV Road', line: 'yellow', type: 'interchange', operational: true },
      { stationId: 'YL02', name: 'Ragigudda', line: 'yellow', type: 'mid_line', operational: true },
      { stationId: 'YL03', name: 'Jayadeva Hospital', line: 'yellow', type: 'mid_line', operational: true },
      { stationId: 'YL04', name: 'BTM Layout', line: 'yellow', type: 'residential_area', operational: true },
      { stationId: 'YL05', name: 'Central Silk Board', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL06', name: 'Bommanahalli', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL07', name: 'Hongasandra', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL08', name: 'Kudlu Gate', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL09', name: 'Singasandra', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL10', name: 'Hosa Road', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL11', name: 'Beratena Agrahara', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL12', name: 'Electronic City', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL13', name: 'Konappana Agrahara', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL14', name: 'Huskur Road', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL15', name: 'Hebbagodi', line: 'yellow', type: 'tech_hub', operational: true },
      { stationId: 'YL16', name: 'Bommasandra', line: 'yellow', type: 'tech_hub', operational: true }
    ];

module.exports = allStations;
